spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mars-x.rwlb.rds.aliyuncs.com:3306/classical_chinese?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: cc_admin
    password: ${MYSQL_PASSWORD:fqg#U2%#_ODD32fkp}

wechat:
  app-id: wxa192d18a50c75dca
  app-secret: ${WECHAT_APP_SECRET:3e60f050d617781d3a89c9a209d053c4}
