spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mars-x.rwlb.rds.aliyuncs.com:3306/classical_chinese?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: cc_admin
    password: ${MYSQL_PASSWORD:fqg#U2%#_ODD32fkp}

wechat:
  app-id: wx00adcbea9d77ba88
  app-secret: ${WECHAT_APP_SECRET:762a6a02dba5ba0b7f16650c5655ba95}
