spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/classical_chinese?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: ${MYSQL_PASSWORD:123456}

wechat:
  app-id: wxa192d18a50c75dca
  app-secret: ${WECHAT_APP_SECRET:3e60f050d617781d3a89c9a209d053c4}
